# Configure PostgreSQL resources
# Configure PostgreSQL credentials
postgresql:
  postgresqlPassword: "postgres"
  postgresqlDatabase: "nextcloud"

  persistence:
    size: 30Gi
    storageClass: rook-ceph-block

  primary:
    affinity:
      podAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: app
              operator: In
              values:
              - nextcloud
          topologyKey: kubernetes.io/hostname 

  rbac:
    create: true

# Configure Redis resources
# Configure Redis credentials
redis:
  cluster:
    enabled: false

  master:
    affinity:
      podAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: app
              operator: In
              values:
              - nextcloud
          topologyKey: kubernetes.io/hostname 

  usePassword: false

  rbac:
    create: true
