# Configure PostgreSQL resources
# Configure PostgreSQL credentials
postgresql:
  postgresqlPassword: "postgres"
  postgresqlDatabase: "nextcloud"

  persistence:
    size: 20Gi
    storageClass: rook-ceph-block

  rbac:
    create: true

# Configure Redis resources
# Configure Redis credentials
redis:
  cluster:
    enabled: false

  usePassword: false

  master:
    resources:
      requests:
        cpu: 2
        memory: 36Gi

  rbac:
    create: true
