apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud
  namespace: storage
  labels:
    app: nextcloud
spec:
  selector:
    matchLabels:
      app: nextcloud
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      containers:
      - name: nextcloud
        image: nextcloud:21.0.0-apache
        ports:
        - containerPort: 80
        volumeMounts:
        - name: storage-pv
          mountPath: "/var/www/html"
          subPath: "nextcloud"
        env:
        - name: POSTGRES_DB
          value: {{ .Values.postgresql.postgresqlDatabase }}
        - name: POSTGRES_USER
          value: {{ .Values.postgresql.postgresqlUsername }}
        - name: POSTGRES_PASSWORD
          value: {{ .Values.postgresql.postgresqlPassword }}
        - name: POSTGRES_HOST
          value: "nextcloud-postgresql.storage"
        - name: NEXTCLOUD_TRUSTED_DOMAINS
          value: "localhost,nc.faust.dev,nc.kzh.dev"
        - name: REDIS_HOST
          value: "nextcloud-redis-master.storage"
      volumes:
      - name: storage-pv
        persistentVolumeClaim:
          claimName: storage
